{"name": "test_demo2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == -1", "trace": "self = <test_mark标签.Test_Demo object at 0x0000019A7CFD2F10>\n\n    @pytest.mark.demo2\n    def test_demo2(self):\n        a = 5\n        b = -1\n>       assert a == b\nE       assert 5 == -1\n\ntest_mark标签.py:15: AssertionError"}, "start": 1701408934291, "stop": 1701408934291, "uuid": "90bbd69a-303f-4856-9641-d5d2d63d89fa", "historyId": "591faeae585796146de8703243f3657f", "testCaseId": "591faeae585796146de8703243f3657f", "fullName": "test_mark标签.Test_Demo#test_demo2", "labels": [{"name": "tag", "value": "demo2"}, {"name": "suite", "value": "test_mark标签"}, {"name": "subSuite", "value": "Test_Demo"}, {"name": "host", "value": "QuMoSi"}, {"name": "thread", "value": "17248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark标签"}]}