{"name": "test_simple_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:6: AssumptionFailure\n>>\tpytest.assume(1==0)\nAssertionError: assert False\n\ntest_assume.py:8: AssumptionFailure\n>>\tpytest.assume(False)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:6: AssumptionFailure\nE               >>\tpytest.assume(1==0)\nE               AssertionError: assert False\nE               \nE               test_assume.py:8: AssumptionFailure\nE               >>\tpytest.assume(False)\nE               AssertionError: assert False\n\nD:\\Miniconda\\Lib\\site-packages\\six.py:718: FailedAssumption"}, "start": 1701430293981, "stop": 1701430294113, "uuid": "72364c7e-4b59-419b-a4b1-d09e2368bc8d", "historyId": "4abe22833711ccb9a1fb9c03c0ff2fb2", "testCaseId": "4abe22833711ccb9a1fb9c03c0ff2fb2", "fullName": "test_assume#test_simple_assume", "labels": [{"name": "suite", "value": "test_assume"}, {"name": "host", "value": "QuMoSi"}, {"name": "thread", "value": "14004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume"}]}